# name of the file
# name:
# # trigger
# on:
# # jobs you will  be running
# jobs:
name: Deploy a simple application
on:
  push:
    branches:
      - master

jobs:
  deploy_application_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: "say hello"
        run: |
          echo "Hello everyone!"
      - name: Checkout from .github directory
        uses: actions/checkout@v4

      - name: "List directory 2"
        run:
          ls ubuntu-latest
      - name: "Build Docker image"
        run:
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/sampleapp123 .
          # . is because we have checked out into the root directory which already has he docker file
        
      - name: "login to DockerHub"
        run:
          docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_PASSWORD}}
          
      - name: "Push to DockerHub"
        run:
          docker push ${{secrets.DOCKERHUB_USERNAME}}/Sampleapp123
        